In [3]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import csv

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

In [10]:
y_true_label = pd.read_csv('edit_subject_007_01__y.csv', names=['label']).values
y_pred_label = pd.read_csv('edit_subject_007_01__y_prediction_6.csv', names=['label']).values
for i in range(8):
    y_pred_label = np.insert(y_pred_label, 0, 0, axis=0)
matrix = confusion_matrix(y_pred_label, y_true_label)
print(matrix)

[[6174   60   56  973]
 [  45  322    0   20]
 [  61    0  479   11]
 [ 861    0    5 1708]]
